name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-docker:
    runs-on: ubuntu-latest
    needs: publish-npm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $username -p $password 

      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build the Docker image
        id: build-docker-image
        run: docker build -t agentvoiceresponse/avr-docs-mcp:latest -t agentvoiceresponse/avr-docs-mcp:${{ steps.package-version.outputs.current-version}} .

      - name: Push the Docker image
        id: push-docker-image
        run: docker push agentvoiceresponse/avr-docs-mcp:latest && docker push agentvoiceresponse/avr-docs-mcp:${{ steps.package-version.outputs.current-version}}